---
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 600
  become: yes

    