name: Run Ansible Setup

on: workflow_dispatch
#  push:
#    branches:
#      - main # デプロイ対象のブランチを指定

jobs:
  setup:
    runs-on: [ self-hosted ]

    container:
      image: ghcr.io/daik67/ansible-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.MY_SEC }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo  "${{ secrets.SSH_MYSEC }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 10.0.2.21 >> ~/.ssh/known_hosts
#        ssh-keyscan server1 server2 >> ~/.ssh/known_hosts
#        ssh-keyscan -f servers.txt >> ~/.ssh/known_hosts

    - name: Run Ansible Setup
      run: |
        ansible --version
        cd ./ansible_project
        ansible-playbook -i inventories/production/hosts -e "ansible_user=adminuser" site.yml -vvv
